### ISSUE TITLE
Update IdentityModel to 4.0.0

### ISSUE THREAD

**Issue by sergiypopovych7576** [XeroAPI/Xero-NetStandard#126]
**SDK you're using (please complete the following information):**
 - Version 
![image](https://user-images.githubusercontent.com/39326394/74524770-59142500-4f28-11ea-837c-aae2678f2512.png)

**Describe the bug**
IdentityModel v3.10.10 which is used in Xero.NetStandard.OAuth2Client is incompatible with IdentityModel v4.0.0

**To Reproduce**
1. You need to have project with IdentityModel v4.0.0 in solution
2. You install following packages for Xero api which are using v3.10.10
![image](https://user-images.githubusercontent.com/39326394/74524846-7cd76b00-4f28-11ea-8b45-83d45d8d0b76.png)
3.At runtime, there is an error while calling RequestAccessTokenAsync() method
![image](https://user-images.githubusercontent.com/39326394/74525219-3f271200-4f29-11ea-8034-789259fe0640.png)
![image](https://user-images.githubusercontent.com/39326394/74525232-46e6b680-4f29-11ea-9911-771f79c639c4.png)

**Expected behavior**
Expected to request flow normally and return token

**Additional context**
If I add your libraries manually and update IdentityModel version to 4.0.0 everything works as expected.

**Comment by jenksguo** [comment]
Hi @sergiypopovych7576, we will investigate and include a fix in the next OAuth2Client release.

**Comment by sergiypopovych7576** [comment]
Same issue for Xero.NetStandard.OAuth2 and RestSharp library. If I update it manually (to 106.10.1) everything works.
![image](https://user-images.githubusercontent.com/39326394/74664758-fc726d80-51a6-11ea-8da0-533cbb3f3e3f.png)

**Comment by jenksguo** [comment]
@sergiypopovych7576 , thanks for verifying this. This is pending update and some testing myself before I release it.

**Comment by chrismoutray** [comment]
> Same issue for Xero.NetStandard.OAuth2 and RestSharp library. If I update it manually (to 106.10.1) everything works.
> ![image](https://user-images.githubusercontent.com/39326394/74664758-fc726d80-51a6-11ea-8da0-533cbb3f3e3f.png)

Can you confirm what you mean by manual update?
If I Manage the Nugets and Update I get the same issue.

**Comment by karandesai28** [comment]
Is this issue solved yet?

**Comment by jenksguo** [comment]
@karandesai28 @chrismoutray @sergiypopovych7576 We have pushed out a new release [1.0.0](https://www.nuget.org/packages/Xero.NetStandard.OAuth2Client/1.0.0) for OAuth2Client to use HttpClient instead of IHttpClientFactory which I believe was the cause of the dependency. 

https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2Client/src/Client/XeroClient.cs#L110

**Comment by karandesai28** [comment]
Thanks for the update 👍

**Comment by jenksguo** [comment]
@karandesai28 Would you be able to try this and confirm? If it works we should close this issue. :-)

**Comment by sergiypopovych7576** [comment]
Not resolved. The Identity dependency still throws an error 
https://github.com/XeroAPI/Xero-NetStandard/blob/master/Xero.NetStandard.OAuth2Client/Xero.NetStandard.OAuth2Client.csproj
line: 15 -> IdentityModel v3.10.10

![image](https://user-images.githubusercontent.com/39326394/89293540-c34f8c00-d666-11ea-94e8-bce2842822f1.png)

**Comment by sergiypopovych7576** [comment]
Can we update IdentityModel package to latest 4.3.1?

**Comment by jenksguo** [comment]
Hi @sergiypopovych7576 there has been an issue with merging. Please expect an update in 2 days.

**Comment by jenksguo** [comment]
Hi @sergiypopovych7576, new[ release v1.1.0](https://www.nuget.org/packages/Xero.NetStandard.OAuth2Client/1.1.0) addressed this issue alone with a few other issues.

**Comment by jenksguo** [comment]
@karandesai28 should be resolved in v1.1.0, please help to test in your specific environment.

**Comment by jenksguo** [comment]
Closing this issue, please re-open if there is any other issues found with this.

**Comment by sergiypopovych7576** [comment]
@jenksguo, now I got same issue for RestSharp. 
You got 106.6.7
![image](https://user-images.githubusercontent.com/39326394/89775091-c982b400-db0f-11ea-9182-c5c34cd18738.png)
![image](https://user-images.githubusercontent.com/39326394/89775325-41e97500-db10-11ea-8115-062bb662c10e.png)

I got 106.10.1

**Comment by sergiypopovych7576** [comment]
@jenksguo can we reopen this issue?

**Comment by jenksguo** [comment]
Hey @sergiypopovych7576 the original issue was on [Xero.Netstandard.Oauth2Client package](https://www.nuget.org/packages/Xero.NetStandard.OAuth2Client/) IdentityModel not being on v4.0.0. I believe that has been addressed. 


The main part of the API is the Xero.Netstandard.Oauth2 which has the methods to communicate with Xero. Were you expecting the RestSharp of this library to be on a higher version? If so this is mentioned in [this issue](https://github.com/XeroAPI/Xero-NetStandard/issues/198), the developer is asking this to be over 106.11.X.

Would you be able to provide the challenges you have with the lower version of RestSharp?

**Comment by jenksguo** [comment]
@sergiypopovych7576 @karandesai28 in v3.5.0 I have updated the restsharp dependency to 106.11.4. :-) 

I will close this issue in a week time if there is no other updates from you.

**Comment by jenksguo** [comment]
Let me know if you would like to reopen this issue.
