### ISSUE TITLE
IdentityModel 7.0.0 compatibility issue

### ISSUE THREAD

**Issue by neoGeneva** [XeroAPI/Xero-NetStandard#520]
I get the following error when using IdentityModel 7.0.0 with Xero.NetStandard.OAuth2 6.0.0

```
System.MissingMethodException: Method not found: 'System.String IdentityModel.Client.RequestUrlExtensions.CreateAuthorizeUrl(IdentityModel.Client.RequestUrl, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.String, System.Nullable`1<Int32>, System.String, System.String, IdentityModel.Client.Parameters)'.
   at Xero.NetStandard.OAuth2.Client.XeroClient.BuildLoginUri(String state, String scope)
   at Xero.NetStandard.OAuth2.Client.XeroClient.BuildLoginUri(String state)
   at Xero.NetStandard.OAuth2.Client.XeroClient.BuildLoginUri()
```

**Comment by flexer911** [comment]
I also came across the same issue yesterday. I had to downgrade IdentityModel to v6.2.0 to get it working again. 
Looks like IdentityModel has changes the method signature of "CreateAuthorizeUrl()".

**Comment by JamesOPCS** [comment]
Yep, also got this issue myself.

**Comment by ankushkhandare95** [comment]
Fix is available in the latest version of .net sdk 9.2.0

**Comment by neoGeneva** [comment]
Hey @ankushkhandare95, this doesn't seem to be fixed. Looks like there's a new version of `Xero.NetStandard.OAuth2` but the issue is in `XeroClient` which is in `Xero.NetStandard.OAuth2Client`.

**Comment by lucasriechelmann** [comment]
I am getting Method Not Found in the Accounting API method UpdateOrCreateContactsAsync

**Comment by ReviveDigitalTeam** [comment]
This issue is not resolved yet, please patch `Xero.NetStandard.OAuth2Client`

**Comment by slykiwi** [comment]
Did this get resolved? I have the same issue when trying to add new Xero tennants:
"Method not found: 'System.String IdentityModel.Client.RequestUrlExtensions.CreateAuthorizeUrl"

Version: Xero.NetStandard.OAuth2 - 9.2.0.
Xero.NetStandard.OAuth2Client - 1.6.0
IdentityModel - 7.0.0

**Comment by neoGeneva** [comment]
@slykiwi No, I don't believe so. Though for me it's less of an issue now since `IdentityModel` is now `Duende.IdentityModel`, so while Xero uses the old version, I can use the newer version without any versioning issues.
